# Generated by Django 4.1.5 on 2023-01-19 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addcorpus', '0002_alter_corpus_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_json', models.JSONField(help_text='Search query JSON. Uses elasticseach query DSL')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(null=True)),
                ('aborted', models.BooleanField(default=False, help_text='Whether the download was prematurely ended')),
                ('transferred', models.BigIntegerField(help_text='Number of transferred (e.g. actually downloaded) documents. Note that this does not say anything about the size of those documents.', null=True)),
                ('total_results', models.BigIntegerField(help_text='Number of total results available for the query', null=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='addcorpus.corpus', to_field='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
    ]
