# Generated by Django 4.1.5 on 2023-01-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_add_query_add_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='download_type',
            field=models.CharField(choices=[('search_results', 'Search results'), ('date_term_frequency', 'Term frequency (timeline)'), ('aggregate_term_frequency', 'Term frequency (histogram)')], help_text='Type of download (search results or a type of visualisation)', max_length=126),
        ),
        migrations.AlterField(
            model_name='download',
            name='filename',
            field=models.FilePathField(help_text='Path to the assembled CSV file', max_length=254, null=True, path='/home/luka/Documents/I-analyzer/I-analyzer-django/backend/ianalyzer/../api/csv_files'),
        ),
        migrations.AlterField(
            model_name='download',
            name='parameters',
            field=models.JSONField(help_text='JSON parameters for the download request that was made to the backend'),
        ),
        migrations.AlterField(
            model_name='query',
            name='aborted',
            field=models.BooleanField(default=False, help_text='Whether the download was prematurely ended'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_json',
            field=models.JSONField(help_text='Search query JSON. Uses elasticseach query DSL'),
        ),
        migrations.AlterField(
            model_name='query',
            name='total_results',
            field=models.BigIntegerField(help_text='Number of total results available for the query', null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='transferred',
            field=models.BigIntegerField(help_text='Number of transferred (e.g. actually downloaded) documents. Note that this does not say anything about the size of those documents.', null=True),
        ),
    ]
