# Generated by Django 4.1.5 on 2023-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='started',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
