# Generated by Django 4.1.5 on 2023-04-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_query_started'),
        ('api', '0002_convert_to_es_query'),
    ]

    operations = [
    ]
