# Generated by Django 4.1.13 on 2023-12-14 09:47

from django.db import migrations
from api.migration_utils.es_query_api_query import es_query_to_api_query, api_query_to_es_query

def es_queries_to_api_queries(apps, schema_editor):
    Query = apps.get_model('api', 'Query')
    queries = Query.objects.all()
    for query in queries:
        query.query_json = es_query_to_api_query(query.query_json)
        query.save()

def api_queries_to_es_queries(apps, schema_editor):
    Query = apps.get_model('api', 'Query')
    queries = Query.objects.all()
    for query in queries:
        query.query_json = api_query_to_es_query(query.query_json)
        query.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_convert_to_es_query'),
    ]

    operations = [
                migrations.RunPython(
            code=es_queries_to_api_queries,
            reverse_code=api_queries_to_es_queries,
        )
    ]
