# base image
FROM docker.io/library/node:22-alpine as base

RUN apk update && apk add --no-cache --virtual .gyp python3 make g++
# Install Chrome
RUN apk add chromium
ENV CHROME_BIN='/usr/bin/chromium-browser'
RUN apk del .gyp
