services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ianalyzer-db:/var/lib/mysql
  backend:
    build:
      context: ./backend
    depends_on:
      - db
      - celery
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      FLASK_DEBUG: 1
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - type: bind
        source: ./backend
        target: /backend
      - type: bind
        source: ~/corpora
        target: /corpora
    command: bash -c "flask run --host=0.0.0.0"
  frontend:
    build:
      context: ./frontend
    ports:
      - 127.0.0.1:4200:4200
    volumes:
      - type: bind
        source: ./frontend/src
        target: /frontend/src
    command: sh -c "yarn start-docker"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - node.name=ianalyzer-node
      - discovery.type=single-node
      - cluster.name=ianalizer-es-data-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=$ELASTIC_ROOT_PASSWORD
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ianalyzer-es:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server
    ports:
      - 127.0.0.1:6379:6379
  celery:
    build:
      context: ./backend
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    command: celery -A ianalyzer.runcelery.celery_app worker --loglevel=info
    depends_on:
      - redis


volumes:
  ianalyzer-db:
  ianalyzer-es: