services:
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    command: bash -c "flask run"
  frontend:
    build:
      context: ./frontend
    ports:
      - 4200:4200
    volumes:
      - type: bind
        source: ./frontend/src
        target: /frontend/src
    command: sh -c "yarn start-docker"
