services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ianalyzer-db:/var/lib/mysql
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    command: bash -c "flask run --host=0.0.0.0"
  frontend:
    build:
      context: ./frontend
    ports:
      - 127.0.0.1:4200:4200
    volumes:
      - type: bind
        source: ./frontend/src
        target: /frontend/src
    command: sh -c "yarn start-docker"

volumes:
  ianalyzer-db: