# Generated by Django 4.2.17 on 2025-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaliastask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16),
        ),
        migrations.AddField(
            model_name='createindextask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16),
        ),
        migrations.AddField(
            model_name='deleteindextask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16),
        ),
        migrations.AddField(
            model_name='populateindextask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16),
        ),
        migrations.AddField(
            model_name='removealiastask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16),
        ),
        migrations.AddField(
            model_name='updateindextask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16),
        ),
        migrations.AddField(
            model_name='updatesettingstask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16),
        ),
    ]
