# Generated by Django 4.2.17 on 2025-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0002_addaliastask_status_createindextask_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaliastask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='createindextask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='deleteindextask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='populateindextask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='removealiastask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='updateindextask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='updatesettingstask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
