# Generated by Django 4.2.14 on 2024-11-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0002_updatesettingstask'),
    ]

    operations = [
        migrations.AddField(
            model_name='createindextask',
            name='production_settings',
            field=models.BooleanField(default=False, help_text='configure index settings for a production environment'),
        ),
    ]
