# Generated by Django 4.1.5 on 2023-01-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0001_add_corpus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name_plural': 'corpora'},
        ),
    ]
