# Generated by Django 4.1.9 on 2023-08-02 15:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0002_alter_corpus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='internal name for the field', max_length=126)),
                ('display_name', models.CharField(help_text='name that is displayed in the interface', max_length=256)),
                ('display_type', models.CharField(choices=[('text_content', 'text content'), ('text', 'text'), ('keyword', 'keyword'), ('date', 'date'), ('integer', 'integer'), ('float', 'float')], help_text='as what type of data this field is rendered in the interface', max_length=16)),
                ('description', models.CharField(help_text='explanatory text to be shown in the interface', max_length=254, null=True)),
                ('search_filter', models.JSONField(help_text='specification of the search filter for this field (if any)', null=True)),
                ('results_overview', models.BooleanField(default=False, help_text='whether this field is shown in document previews in search results')),
                ('csv_core', models.BooleanField(default=False, help_text='whether this field is included in search results downloads by default')),
                ('search_field_core', models.BooleanField(default=False, help_text='whether this field is pre-selected when choosing search fields')),
                ('visualizations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('resultscount', 'Number of results'), ('termfrequency', 'Frequency of the search term'), ('ngram', 'Neighbouring words'), ('wordcloud', 'Most frequent words')], max_length=16), help_text='visualisations for this field', null=True, size=None)),
                ('visualization_sort', models.CharField(choices=[('key', 'By the value of the field'), ('value', 'By frequency')], help_text='if the field has results/term frequency charts: how is the x-axis sorted?', max_length=8, null=True)),
                ('es_mapping', models.JSONField(help_text='specification of the elasticsearch mapping of this field')),
                ('indexed', models.BooleanField(default=True, help_text='whether this field is indexed in elasticsearch')),
                ('hidden', models.BooleanField(default=False, help_text='whether this field is hidden in the interface')),
                ('required', models.BooleanField(default=False, help_text='whether this field is required')),
                ('sortable', models.BooleanField(default=False, help_text='whether search results can be sorted on this field')),
                ('primary_sort', models.BooleanField(default=False, help_text='if sortable: whether this is the default method of sorting search results')),
                ('searchable', models.BooleanField(default=False, help_text='whether this field is listed when selecting search fields')),
                ('downloadable', models.BooleanField(default=True, help_text='whether this field can be included in search results downloads')),
                ('corpus', models.ForeignKey(help_text='corpus that this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='addcorpus.corpus')),
            ],
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.UniqueConstraint(fields=('corpus', 'name'), name='unique_name_for_corpus'),
        ),
    ]
