# Generated by Django 4.1.9 on 2023-08-03 12:41

import addcorpus.validators
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('addcorpus', '0003_add_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='allow_image_download',
            field=models.BooleanField(default=False, help_text='whether users can download document scans'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='category',
            field=models.CharField(choices=[('newspaper', 'Newspapers'), ('parliament', 'Parliamentary debates'), ('periodical', 'Periodicals'), ('finance', 'Financial reports'), ('ruling', 'Court rulings'), ('review', 'Online reviews'), ('inscription', 'Funerary inscriptions'), ('oration', 'Orations'), ('book', 'Books')], default='newspaper', help_text='category/medium of documents in this dataset', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='description_page',
            field=models.CharField(blank=True, help_text='filename of the markdown documentation file for this corpus', max_length=128),
        ),
        migrations.AddField(
            model_name='corpus',
            name='document_context',
            field=models.JSONField(help_text='specification of how documents are grouped into collections', null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='es_alias',
            field=models.SlugField(blank=True, help_text='alias assigned to the corpus index in elasticsearch', max_length=126),
        ),
        migrations.AddField(
            model_name='corpus',
            name='es_index',
            field=models.SlugField(default='changeme', help_text='name of the corpus index in elasticsearch', max_length=126),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='image',
            field=models.CharField(default='image.jpg', help_text='filename of the corpus image', max_length=126),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8, validators=[addcorpus.validators.validate_language_code]), default=['en'], help_text='languages used in the content of the corpus (from most to least frequent)', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='max_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 14, 40, 32, 908822), help_text='latest date for the data in the corpus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='min_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 14, 40, 44, 809580), help_text='earliest date for the data in the corpus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='scan_image_type',
            field=models.CharField(blank=True, help_text='MIME type of scan images', max_length=64),
        ),
        migrations.AddField(
            model_name='corpus',
            name='title',
            field=models.CharField(default='Temporary title', help_text='title of the corpus in the interface', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='word_models_present',
            field=models.BooleanField(default=False, help_text='whether this corpus has word models'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='description',
            field=models.CharField(blank=True, default='', help_text='short description of the corpus', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corpus',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='groups that have access to this corpus', related_name='corpora', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='name',
            field=models.SlugField(help_text='internal name of the corpus', max_length=126, unique=True),
        ),
    ]
