# Generated by Django 4.1.9 on 2023-09-13 16:15

import addcorpus.validation.creation
from django.db import migrations, models


def validate_image_filename_extension(filename):
    allowed = ['.jpeg', '.jpg', '.png', '.JPG']
    addcorpus.validation.creation.validate_filename_extension(filename, allowed)


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0004_alter_corpusconfiguration_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='description_page',
            field=models.CharField(blank=True, help_text='filename of the markdown documentation file for this corpus', max_length=128, validators=[addcorpus.validation.creation.validate_markdown_filename_extension]),
        ),
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='image',
            field=models.CharField(help_text='filename of the corpus image', max_length=126, validators=[validate_image_filename_extension]),
        ),
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='scan_image_type',
            field=models.CharField(blank=True, help_text='MIME type of scan images', max_length=64, validators=[addcorpus.validation.creation.validate_mimetype]),
        ),
        migrations.AlterField(
            model_name='field',
            name='es_mapping',
            field=models.JSONField(help_text='specification of the elasticsearch mapping of this field', validators=[addcorpus.validation.creation.validate_es_mapping]),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.SlugField(help_text='internal name for the field', max_length=126, validators=[addcorpus.validation.creation.validate_name_is_not_a_route_parameter]),
        ),
        migrations.AlterField(
            model_name='field',
            name='search_filter',
            field=models.JSONField(blank=True, help_text='specification of the search filter for this field (if any)', validators=[addcorpus.validation.creation.validate_search_filter]),
        ),
    ]
