# Generated by Django 4.1.9 on 2023-08-03 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0004_expand_corpus_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, default='', help_text='explanatory text to be shown in the interface', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='search_filter',
            field=models.JSONField(blank=True, default={}, help_text='specification of the search filter for this field (if any)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='visualization_sort',
            field=models.CharField(blank=True, choices=[('key', 'By the value of the field'), ('value', 'By frequency')], default='', help_text='if the field has results/term frequency charts: how is the x-axis sorted?', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='visualizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('resultscount', 'Number of results'), ('termfrequency', 'Frequency of the search term'), ('ngram', 'Neighbouring words'), ('wordcloud', 'Most frequent words')], max_length=16), blank=True, default=[], help_text='visualisations for this field', size=None),
            preserve_default=False,
        ),
    ]
