# Generated by Django 4.1.9 on 2023-08-07 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0004_alter_field_visualizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='visualizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('resultscount', 'Number of results'), ('termfrequency', 'Frequency of the search term'), ('ngram', 'Neighbouring words'), ('wordcloud', 'Most frequent words')], max_length=16), blank=True, default=list, help_text='visualisations for this field', size=None),
        ),
    ]
