# Generated by Django 4.1.9 on 2023-08-07 13:51

import addcorpus.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0005_alter_field_visualizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=8, validators=[addcorpus.validators.validate_language_code]), help_text='languages used in the content of the corpus (from most to least frequent)', size=None),
        ),
    ]
