# Generated by Django 4.1.9 on 2023-08-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0005_alter_field_description_alter_field_search_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='display_type',
            field=models.CharField(choices=[('text_content', 'text content'), ('text', 'text'), ('keyword', 'keyword'), ('date', 'date'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean')], help_text='as what type of data this field is rendered in the interface', max_length=16),
        ),
    ]
