# Generated by Django 4.1.13 on 2023-12-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0006_alter_corpusconfiguration_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='display_type',
            field=models.CharField(choices=[('text_content', 'text content'), ('text', 'text'), ('keyword', 'keyword'), ('date', 'date'), ('date_range', 'date_range'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean')], help_text='as what type of data this field is rendered in the interface', max_length=16),
        ),
    ]
