# Generated by Django 4.1.9 on 2023-08-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0006_alter_corpusconfiguration_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='active',
        ),
    ]
