# Generated by Django 4.1.9 on 2023-08-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0006_alter_field_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='active',
            field=models.BooleanField(default=True, help_text='removing a corpus from settings will set it to inactive'),
        ),
    ]
