# Generated by Django 4.2.7 on 2024-02-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0007_alter_field_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='display_type',
            field=models.CharField(choices=[('text_content', 'text content'), ('text', 'text'), ('keyword', 'keyword'), ('date', 'date'), ('date_range', 'date_range'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('geo_point', 'geo_point')], help_text='as what type of data this field is rendered in the interface', max_length=16),
        ),
    ]
