# Generated by Django 4.2.10 on 2024-03-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0008_alter_field_display_type_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusconfiguration',
            name='direct_download_limit',
            field=models.IntegerField(default=1000, help_text='limit of how many documents can be downloaded without a Celery task'),
        ),
    ]
