# Generated by Django 4.2.7 on 2024-03-05 15:30

import addcorpus.validation.creation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0008_alter_field_display_type_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusconfiguration',
            name='citation_page',
            field=models.CharField(blank=True, help_text='filename of the citation specification (in markdown) for this corpus', max_length=128, validators=[addcorpus.validation.creation.validate_markdown_filename_extension]),
        ),
    ]
