# Generated by Django 4.2.10 on 2024-03-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0010_remove_field_primary_sort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='active',
            field=models.BooleanField(default=False, help_text='an inactive corpus is hidden from the search interface'),
        ),
    ]
