# Generated by Django 4.2.10 on 2024-03-13 11:27

import addcorpus.validation.creation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0011_corpus_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusconfiguration',
            name='language_field',
            field=models.CharField(blank=True, help_text='name of the field that specifies the language of documents (if any);required to use "dynamic" language on fields'),
        ),
        migrations.AddField(
            model_name='field',
            name='language',
            field=models.CharField(blank=True, help_text='specification for the language of this field; can be blank, an IETF tag, or "dynamic"; "dynamic" means the language is determined by the language_field of the corpus configuration', max_length=64, validators=[addcorpus.validation.creation.validate_field_language]),
        ),
    ]
