# Generated by Django 4.2.10 on 2024-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0012_corpusconfiguration_language_field_field_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='document_context',
            field=models.JSONField(blank=True, default=dict, help_text='specification of how documents are grouped into collections'),
        ),
    ]
