# Generated by Django 4.2.10 on 2024-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0013_alter_field_visualizations_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='has_python_definition',
            field=models.BooleanField(default=False, help_text='whether the configuration of this corpus is determined by a Python module (some features are only available for Python-based corpora)'),
        ),
    ]
