# Generated by Django 4.2.10 on 2024-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0014_corpus_has_python_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='image',
            field=models.ImageField(blank=True, help_text='image that can be used for the corpus in the interface', null=True, upload_to='corpus_images'),
        ),
    ]
