# Generated by Django 4.2.10 on 2024-04-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0015_alter_corpusconfiguration_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpusconfiguration',
            name='citation_page',
        ),
        migrations.RemoveField(
            model_name='corpusconfiguration',
            name='description_page',
        ),
        migrations.CreateModel(
            name='CorpusDocumentationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('general', 'General information'), ('citation', 'Citation'), ('license', 'Licence'), ('wordmodels', 'Word models')], default='general', help_text='the type of documentation', max_length=16)),
                ('content', models.TextField(help_text='markdown contents of the documentation')),
                ('corpus_configuration', models.ForeignKey(help_text='configuration that this page documents', on_delete=django.db.models.deletion.CASCADE, related_name='documentation_pages', to='addcorpus.corpusconfiguration')),
            ],
        ),
        migrations.AddConstraint(
            model_name='corpusdocumentationpage',
            constraint=models.UniqueConstraint(fields=('corpus_configuration', 'type'), name='unique_documentation_type_for_corpus'),
        ),
    ]
