# Generated by Django 4.2.11 on 2024-04-10 13:37

from typing import Dict

from django.db import migrations, models
from django.core.exceptions import ValidationError
from jsonschema.exceptions import ValidationError as JSONSchemaValidationError

from addcorpus.json_corpora.validate import validate

def validate_source_data_configuration(source_data: Dict) -> None:
    if source_data == {}:
        return
    try:
        validate(source_data, 'properties', 'source_data')
    except JSONSchemaValidationError as e:
        raise ValidationError(
            ['Corpus source data schema validation failed', e])


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0016_alter_corpusconfiguration_document_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusconfiguration',
            name='source_data',
            field=models.JSONField(blank=True, default=dict, help_text='information about the source data files (e.g. file type)', validators=[validate_source_data_configuration]),
        ),
    ]
