# Generated by Django 4.2.11 on 2024-04-10 13:37

import addcorpus.validation.creation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0016_alter_corpusconfiguration_document_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusconfiguration',
            name='source_data',
            field=models.JSONField(blank=True, default=dict, help_text='information about the source data files (e.g. file type)', validators=[addcorpus.validation.creation.validate_source_data_configuration]),
        ),
    ]
