# Generated by Django 4.2.11 on 2024-04-10 13:58

from typing import Dict

from django.db import migrations, models
from django.core.exceptions import ValidationError
from jsonschema.exceptions import ValidationError as JSONSchemaValidationError

from addcorpus.json_corpora.validate import validate


def validate_field_extract_options(extract_options: Dict) -> None:
    if extract_options == {}:
        return
    try:
        validate(extract_options, 'properties',
                 'fields', 'items', 'properties', 'extract')
    except JSONSchemaValidationError as e:
        raise ValidationError(
            ['Field extract options schema validation failed', e]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0017_source_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='extract_options',
            field=models.JSONField(blank=True, default=dict, help_text='options related to source data extraction', validators=[validate_field_extract_options]),
        ),
    ]
