# Generated by Django 4.2.11 on 2024-04-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0016_remove_corpusconfiguration_citation_page_and_more'),
        ('addcorpus', '0018_field_extract_options'),
    ]

    operations = [
    ]
