# Generated by Django 4.2.10 on 2024-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0019_merge_20240411_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpusconfiguration',
            name='source_data',
        ),
        migrations.RemoveField(
            model_name='field',
            name='extract_options',
        ),
        migrations.AddField(
            model_name='corpusconfiguration',
            name='source_data_delimiter',
            field=models.CharField(blank=True, choices=[(',', 'comma'), (';', 'semicolon'), ('\t', 'tab')], help_text='delimiter used in (CSV) source data files', max_length=1),
        ),
        migrations.AddField(
            model_name='field',
            name='extract_column',
            field=models.CharField(blank=True, help_text='column name in CSV source files from which to extract this field', max_length=64),
        ),
    ]
