# Generated by Django 4.2.10 on 2024-04-16 12:11

import addcorpus.validation.creation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0020_simplify_extraction_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusconfiguration',
            name='data_directory',
            field=models.CharField(blank=True, help_text='path to directory containing source data files', max_length=200, validators=[addcorpus.validation.creation.validate_source_data_directory]),
        ),
    ]
