# Generated by Django 4.2.11 on 2024-07-05 16:30

import addcorpus.validation.creation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0022_add_url_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpusdocumentationpage",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "General information"),
                    ("citation", "Citation"),
                    ("license", "License"),
                    ("terms_of_service", "Terms of service"),
                    ("wordmodels", "Word models"),
                ],
                default="general",
                help_text="the type of documentation",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.SlugField(
                help_text="internal name for the field",
                max_length=126,
                validators=[
                    addcorpus.validation.creation.validate_name_is_not_a_route_parameter,
                    addcorpus.validation.creation.validate_ner_slug,
                ],
            ),
        ),
    ]
