# Generated by Django 4.2.14 on 2024-07-31 13:30

import addcorpus.validation.creation
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0023_alter_corpusdocumentationpage_type_alter_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='category',
            field=models.CharField(blank=True, choices=[('parliament', 'Parliamentary debates'), ('periodical', 'Newspapers and other periodicals'), ('finance', 'Financial reports'), ('ruling', 'Court rulings'), ('review', 'Online reviews'), ('inscription', 'Funerary inscriptions'), ('oration', 'Orations'), ('book', 'Books'), ('informative', 'Informative')], help_text='category/medium of documents in this dataset', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='description',
            field=models.CharField(blank=True, help_text='short description of the corpus', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=8, validators=[addcorpus.validation.creation.validate_language_code]), blank=True, help_text='languages used in the content of the corpus (from most to least frequent)', null=True, size=None),
        ),
    ]
