# Generated by Django 4.2.15 on 2024-11-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0023_alter_corpusdocumentationpage_type_alter_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='position',
            field=models.IntegerField(blank=True, help_text="Field's position within the configuration (order)", null=True),
        ),
    ]
