# Generated by Django 4.2.16 on 2024-11-26 09:40

import addcorpus.validation.creation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0024_remove_field_name_ner_validator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='field',
            name='position',
            field=models.IntegerField(blank=True, help_text="Field's position within the configuration (order)", null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(help_text='internal name for the field', max_length=126, validators=[addcorpus.validation.creation.validate_name_is_not_a_route_parameter, addcorpus.validation.creation.validate_field_name_permissible_characters]),
        ),
    ]
