# Generated by Django 4.2.16 on 2024-11-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0024_field_position'),
        ('addcorpus', '0024_remove_field_name_ner_validator'),
    ]

    operations = [
    ]
