# Generated by Django 4.2.16 on 2024-12-02 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0024_remove_field_name_ner_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='date on which the corpus was added to the database'),
            preserve_default=False,
        ),
    ]
