# Generated by Django 4.2.14 on 2024-08-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0024_alter_corpusconfiguration_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='file containing corpus data', upload_to='corpus_datafiles')),
                ('is_sample', models.BooleanField(default=False, help_text='this file reflects only part of the total data, for use in creating the corpus definition')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addcorpus.corpus')),
            ],
        ),
    ]
