# Generated by Django 4.2.17 on 2024-12-10 13:25

import addcorpus.models
import addcorpus.validation.creation
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0026_corpus_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='category',
            field=models.CharField(blank=True, choices=[('parliament', 'Parliamentary debates'), ('periodical', 'Newspapers and other periodicals'), ('finance', 'Financial reports'), ('ruling', 'Court rulings'), ('review', 'Online reviews'), ('inscription', 'Funerary inscriptions'), ('oration', 'Orations'), ('book', 'Books'), ('informative', 'Informative')], help_text='category/medium of documents in this dataset', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='description',
            field=models.CharField(blank=True, help_text='short description of the corpus', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=8, validators=[addcorpus.validation.creation.validate_language_code]), blank=True, help_text='languages used in the content of the corpus (from most to least frequent)', size=None),
        ),
        migrations.CreateModel(
            name='CorpusDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='file containing corpus data', upload_to=addcorpus.models.CorpusDataFile.upload_path)),
                ('is_sample', models.BooleanField(default=False, help_text='This file is used in creating the corpus definition, it may additonaly reflect (part of) the actual data.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addcorpus.corpus')),
            ],
        ),
    ]
