# Generated by Django 4.2.16 on 2025-01-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0027_alter_corpusconfiguration_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusconfiguration',
            name='max_year',
            field=models.IntegerField(default=0, help_text='lastest year for the data in the corpus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpusconfiguration',
            name='min_year',
            field=models.IntegerField(default=0, help_text='earliest year for the data in the corpus'),
            preserve_default=False,
        ),
    ]
