# Generated by Django 4.2.17 on 2025-02-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0028_corpusconfiguration_minyear_maxyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='min_year',
            field=models.IntegerField(default=1800, help_text='earliest year for the data in the corpus'),
        ),
    ]
