# Generated by Django 4.2.17 on 2025-04-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0029_alter_corpusconfiguration_min_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='max_year',
            field=models.IntegerField(blank=True, help_text='latest year for the data in the corpus', null=True),
        ),
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='min_year',
            field=models.IntegerField(blank=True, help_text='earliest year for the data in the corpus', null=True),
        ),
    ]
