# Generated by Django 4.2.16 on 2025-01-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0029_fill_minyear_maxyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpusconfiguration',
            name='max_date',
        ),
        migrations.RemoveField(
            model_name='corpusconfiguration',
            name='min_date',
        ),
    ]
