# Generated by Django 4.2.17 on 2025-05-01 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addcorpus', '0030_alter_corpusconfiguration_max_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='user that created the corpus and is allowed to edit it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_corpora', to=settings.AUTH_USER_MODEL),
        ),
    ]
