# Generated by Django 4.2.17 on 2025-04-29 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addcorpus', '0030_alter_corpusconfiguration_max_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='users that created the corpus and are allowed to edit it', related_name='owned_corpora', to=settings.AUTH_USER_MODEL),
        ),
    ]
