# Generated by Django 4.2.16 on 2025-01-21 17:08

import addcorpus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0030_remove_corpusconfiguration_max_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='max_year',
            field=models.IntegerField(default=addcorpus.models.default_max_year, help_text='lastest year for the data in the corpus'),
        ),
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='min_year',
            field=models.IntegerField(default=1800, help_text='earliest year for the data in the corpus'),
        ),
    ]
