# Generated by Django 4.2.17 on 2025-06-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0031_corpus_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusdatafile',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='whether the file has been confirmed by the user as correct'),
        ),
        migrations.AlterUniqueTogether(
            name='corpusdatafile',
            unique_together={('corpus', 'confirmed')},
        ),
    ]
