# Generated by Django 4.2.17 on 2025-05-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0031_corpus_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusdatafile',
            name='field_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corpusdatafile',
            name='n_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
