# Generated by Django 4.2.22 on 2025-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0031_corpus_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusconfiguration',
            name='has_named_entities',
            field=models.BooleanField(default=False, help_text='whether this corpus has named entity annotations'),
        ),
    ]
