# Generated by Django 4.2.25 on 2025-10-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0032_corpusconfiguration_has_named_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusdatafile',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='whether the file has been confirmed by the user as correct'),
        ),
        migrations.AlterUniqueTogether(
            name='corpusdatafile',
            unique_together={('corpus', 'confirmed')},
        ),
    ]
