# Generated by Django 4.2.25 on 2025-10-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0033_corpusdatafile_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusdatafile',
            name='original_filename',
            field=models.CharField(blank=True, help_text='original name of the uploaded file (for user form)'),
        ),
    ]
