# Generated by Django 4.2.22 on 2025-10-27 08:15

from django.apps import AppConfig
from django.db import migrations, models

from addcorpus.json_corpora.csv_field_info import get_csv_info


class Migration(migrations.Migration):

    def populate_csv_info(apps: AppConfig, schema_editor):
        '''Populate existing data files with csv info'''
        CorpusDataFile = apps.get_model('addcorpus', 'CorpusDataFile')
        for obj in CorpusDataFile.objects.all():
            if (not obj.csv_info) and (bool(obj.file)):
                obj.csv_info = get_csv_info(obj.file.path)
                obj.save()

    dependencies = [
        ('addcorpus', '0034_corpusdatafile_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusdatafile',
            name='csv_info',
            field=models.JSONField(blank=True, default={}, help_text='contains information on the content of the file, e.g. columns and number of rows'),
        ),
        migrations.RunPython(code=populate_csv_info, reverse_code=migrations.RunPython.noop)
    ]
