# Generated by Django 4.2.25 on 2025-11-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0035_corpusdatafile_csv_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='category',
            field=models.CharField(blank=True, choices=[('parliament', 'Parliamentary debates'), ('periodical', 'Newspapers and other periodicals'), ('finance', 'Financial reports'), ('ruling', 'Laws and rulings'), ('review', 'Reviews and discussions'), ('inscription', 'Funerary inscriptions'), ('oration', 'Orations'), ('book', 'Books'), ('letter', 'Letters and life writing'), ('poetry', 'Poetry and songs'), ('social', 'Social media'), ('other', 'Other')], help_text='category/medium of documents in this dataset', max_length=64, null=True),
        ),
    ]
