# Generated by Django 4.2.25 on 2025-11-05 17:20

import addcorpus.validation.creation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0036_alter_corpusconfiguration_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='data_directory',
            field=models.CharField(blank=True, help_text='Path to directory containing source data files. For database-only corpora, this can be used to override the CorpusDataFile for the corpus.', max_length=200, validators=[addcorpus.validation.creation.validate_source_data_directory]),
        ),
    ]
