# Generated by Django 4.2.14 on 2024-11-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the index in elasticsearch (including version number)', max_length=134)),
                ('server', models.CharField(default='default', help_text='key of the elasticsearch server in the project settings')),
                ('available', models.BooleanField(default=True, help_text='whether the index is currently available on elasticsearch')),
            ],
        ),
    ]
