# Generated by Django 4.2.16 on 2024-11-14 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the server in the project settings', max_length=128, unique=True)),
                ('active', models.BooleanField(default=True, help_text='whether the server is currently included in project settings; servers can be set to inactive rather than deleted to prevent data loss')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the index in elasticsearch', max_length=134)),
                ('available', models.BooleanField(default=False, help_text='whether the index is currently available on elasticsearch')),
                ('server', models.ForeignKey(help_text='server on which the index is found', on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='es.server')),
            ],
            options={
                'verbose_name_plural': 'indices',
            },
        ),
    ]
