# Generated by Django 4.2.14 on 2024-11-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='available',
            field=models.BooleanField(default=False, help_text='whether the index is currently available on elasticsearch'),
        ),
    ]
