# Generated by Django 4.2.14 on 2024-11-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the server in the project settings', max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name_plural': 'indices'},
        ),
    ]
