# Generated by Django 4.2.14 on 2024-11-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0002_server_alter_index_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='active',
            field=models.BooleanField(default=True, help_text='whether the server is currently included in project settings; servers can be set to inactive rather than deleted to prevent data loss'),
        ),
    ]
