# Generated by Django 4.2.14 on 2024-11-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0003_server_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(help_text='name of the server in the project settings', max_length=128, unique=True),
        ),
    ]
