# Generated by Django 4.1.5 on 2023-01-19 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addcorpus', '0002_alter_corpus_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(null=True)),
                ('download_type', models.CharField(choices=[('search_results', 'Search results'), ('date_term_frequency', 'Term frequency (timeline)'), ('aggregate_term_frequency', 'Term frequency (histogram)')], help_text='Type of download (search results or a type of visualisation)', max_length=126)),
                ('parameters', models.JSONField(help_text='JSON parameters for the download request that was made to the backend')),
                ('filename', models.FilePathField(help_text='Path to the assembled CSV file', max_length=254, null=True, path='/home/luka/Documents/I-analyzer/I-analyzer-django/backend/ianalyzer/../api/csv_files')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='addcorpus.corpus', to_field='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
