"""empty message

Revision ID: 2c4d27e46a7f
Revises: 0fc41e3c59c5
Create Date: 2018-12-11 11:10:01.336706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c4d27e46a7f'
down_revision = '0fc41e3c59c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_saml_login', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_idp_login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_idp_login', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_saml_login')
    # ### end Alembic commands ###
