"""empty message

Revision ID: 451fbb98855a
Revises: 3e90c0a00e10
Create Date: 2019-05-09 18:15:06.746115

"""
from alembic import op
import sqlalchemy as sa

import re

from ianalyzer.models import User

# revision identifiers, used by Alembic.
revision = '451fbb98855a'
down_revision = '3e90c0a00e10'
branch_labels = None
depends_on = None


Session = sa.orm.sessionmaker()
saml_pattern = re.compile('[1-9]{3}') # all saml identifiers have at least three numbers

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('saml', sa.Boolean(), nullable=True))
    bind = op.get_bind()
    session = Session(bind=bind)
    for user in session.query(User):
        if saml_pattern.search(user.username):
            user.saml = True
        else:
            user.saml = False
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'saml')
    # ### end Alembic commands ###
