"""empty message

Revision ID: 451fbb98855a
Revises: 3e90c0a00e10
Create Date: 2019-05-09 18:15:06.746115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451fbb98855a'
down_revision = '3e90c0a00e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('saml', sa.Boolean(), nullable=True))
    sql_command = 'UPDATE user SET saml=false;'
    op.execute(sql_command)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'saml')
    # ### end Alembic commands ###
