"""empty message

Revision ID: 76a4b388c00b
Revises: d0374bca3f84
Create Date: 2022-03-08 17:10:46.855349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a4b388c00b'
down_revision = 'd0374bca3f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=126), nullable=True),
    sa.Column('description', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=126), nullable=True),
    sa.Column('description', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('corpora_roles',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('corpus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=126), nullable=True),
    sa.Column('password', sa.String(length=254), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('saml', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('download_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('corpus_name', sa.String(length=254), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.Column('aborted', sa.Boolean(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('transferred', sa.BigInteger(), nullable=True),
    sa.Column('total_results', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query')
    op.drop_table('user')
    op.drop_table('corpora_roles')
    op.drop_table('role')
    op.drop_table('corpus')
    # ### end Alembic commands ###
