# Generated by Django 4.1.9 on 2023-06-07 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addcorpus', '0002_alter_corpus_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=512)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_instances', to='addcorpus.corpus', to_field='name')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tag.tag')),
            ],
        ),
    ]
