# Generated by Django 4.1.9 on 2023-06-14 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0002_alter_corpus_options'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=64)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_instances', to='addcorpus.corpus', to_field='name')),
                ('tags', models.ManyToManyField(related_name='tags', to='tag.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='TagInstance',
        ),
    ]
