# Generated by Django 4.1.9 on 2023-06-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0002_alter_corpus_options'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=512)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_docs', to='addcorpus.corpus', to_field='name')),
                ('tags', models.ManyToManyField(related_name='tagged_docs', to='tag.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='TagInstance',
        ),
    ]
