# Generated by Django 4.1.9 on 2023-06-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0002_alter_corpus_options'),
        ('tag', '0002_taggeddocument_delete_taginstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeddocument',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_docs', to='addcorpus.corpus', to_field='name'),
        ),
        migrations.AlterField(
            model_name='taggeddocument',
            name='doc_id',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='taggeddocument',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_docs', to='tag.tag'),
        ),
    ]
