# Generated by Django 4.1.9 on 2023-08-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_taggeddocument_delete_taginstance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taggeddocument',
            constraint=models.UniqueConstraint(fields=('corpus', 'doc_id'), name='unique_document_ID_for_corpus'),
        ),
    ]
