# Generated by Django 4.1.5 on 2023-02-16 13:04
# Set SITE 1 to whatever is configured in settings.

from django.db import migrations
from django.conf import settings


def update_site_domain(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    s, _ = Site.objects.get_or_create(pk=settings.SITE_ID)
    s.domain = settings.HOST
    s.name = settings.SITE_NAME
    s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_download_limit'),
    ]

    operations = [
        migrations.RunPython(update_site_domain)
    ]
