# Generated by Django 4.1.5 on 2023-01-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_migrate_flask_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='download_limit',
            field=models.IntegerField(default=10000, help_text='Maximum documents that this user can download per query'),
        ),
    ]
