# Generated by Django 4.1.9 on 2023-08-09 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def add_user_profile(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    UserProfile = apps.get_model('users', 'UserProfile')
    db_alias = schema_editor.connection.alias

    for user in CustomUser.objects.all():
        UserProfile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sitedomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_search_history', models.BooleanField(default=True, help_text='Whether to save the search history of this user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            add_user_profile,
            reverse_code=migrations.RunPython.noop,
        )
    ]
