# Generated by Django 4.2.17 on 2025-04-30 13:06

from django.db import migrations, models

def admin_users_can_edit_corpora(apps, schema_editor):
    '''
    Turns on can_edit_corpora for all admins (since that was previously the requirement)
    '''

    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(user__is_staff=True).update(can_edit_corpora=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_saml_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_corpora',
            field=models.BooleanField(default=False, help_text='Whether the user is allowed to edit corpora'),
        ),
        migrations.RunPython(
            admin_users_can_edit_corpora,
            migrations.RunPython.noop,
        )
    ]
