name: Backend build and push after merge of requirements.txt

on:
    workflow_dispatch:
    pull_request:
      branches:
        - develop
      types:
        - closed
      paths:
        - backend/requirements.txt
        - 'docker-compose.yaml'

jobs:
  if_merged:
    name: Build and push backend image
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Backend
      uses: docker/build-push-action@v6
      with:
        context: backend/.
        push: true
        tags: ghcr.io/centrefordigitalhumanities/ianalyzer-backend:latest
