# This workflow will run backend tests on the Python version defined in the backend/Dockerfile

name: Backend unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
    paths:
      - 'backend/**'
      - '.github/workflows/backend*'
      - 'docker-compose.yaml'

jobs:
  backend-test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run backend tests
      run: |
        sudo mkdir -p /ci-data
        docker compose pull elasticsearch
        docker compose --env-file .env-ci run --rm backend pytest
