# This workflow will run backend tests on the Python version defined in the Dockerfiles

name: Backend unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
    paths:
      - 'backend/**'
      - '.github/workflows/backend*'
      - 'docker-compose.yaml'

jobs:
  backend-test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: backend/.
        push: true
        tags: "ghcr.io/uudigitalhumanitieslab/ianalyzer-backend:latest"
        cache-from: type=registry,ref=ghcr.io/uudigitalhumanitieslab/ianalyzer-backend:buildcache
        cache-to: type=registry,ref=ghcr.io/uudigitalhumanitieslab/ianalyzer-backend:buildcache,mode=max
    - name: Run backend tests
      run: |
        sudo mkdir -p /ci-data
        docker-compose --env-file .env-ci run --rm backend pytest
