# This workflow will run backend tests on the Python version defined in the Dockerfiles

name: Backend unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
    paths:
      - 'backend/**'
      - '.github/workflows/**'
      - 'docker-compose.yaml'

jobs:
  backend-test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build backend image, using cache from Github registry
      run: |
        cd backend
        docker build . --tag ghcr.io/uudigitalhumanitieslab/ianalyzer-backend --cache-from=ghcr.io/uudigitalhumanitieslab/ianalyzer-backend
        docker push ghcr.io/uudigitalhumanitieslab/ianalyzer-backend || true
    - name: Run backend tests
      run: |
        cd ..
        mkdir -p /ci-data
        docker-compose --env-file .env-ci run --rm backend pytest
