# This workflow will run frontend tests on the Node version defined in the Dockerfiles

name: Frontend unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend*'
      - 'docker-compose.yaml'

jobs:
  frontend-test:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run frontend unit tests
      run: |
        docker compose --env-file .env-ci run --rm frontend yarn test
