# This workflow will run frontend tests on the Node version defined in the Dockerfiles

name: Frontend unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
    paths:
      - 'frontend/**'

jobs:
  frontend-test:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run frontend tests
      run: |
        docker pull ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend:latest || true
        docker build . --tag ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend:latest --cache-from=ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend:latest
        docker push ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend:latest --cache-from=ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend:latest || true