# This workflow will build the frontend container and then run tests; it will only be triggered when yarn.lock changes

name: Frontend unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'dependabot/**'
    paths:
      - frontend/yarn.lock
      - 'docker-compose.yaml'

jobs:
  frontend-test:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run frontend unit tests
      run: |
        docker compose --env-file .env-ci run --build frontend yarn test
