# This workflow will run frontend tests on the Node version defined in the Dockerfiles

name: Frontend unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
      - 'docker-compose.yaml'

jobs:
  frontend-test:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build frontend image, using cache from Github registry
      run: |
        cd frontend
        docker build . --tag ianalyzer-frontend --cache-from=ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend
        docker push ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend || true
    - name: Run frontend unit tests
      run: |
        docker run ianalyzer-frontend yarn test
