# This workflow will run frontend tests on the Node version defined in the Dockerfiles

name: Frontend unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend*'
      - 'docker-compose.yaml'

jobs:
  frontend-test:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build frontend image, using cache from Github registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend
        cache-from: type=registry, ref=ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend
        cache-to: type=registry, ref=ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend
        file: frontend/Dockerfile
    - name: Run frontend unit tests
      run: |
        docker run ianalyzer-frontend sh -c "yarn prebuild && yarn test"
