name: Frontend build and push after merge of yarn.lock

on:
    pull_request:
      branches:
        - develop
      types:
        - closed
      paths:
        - frontend/yarn.lock
        - 'docker-compose.yaml'

jobs:
  if_merged:
    name: Build and push frontend image
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build frontend image, using cache from Github registry
      uses: docker/build-push-action@v6
      with:
        context: frontend/.
        push: true
        tags: ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend:latest
        cache-from: type=registry,ref=ghcr.io/uudigitalhumanitieslab/ianalyzer-frontend:latest
        cache-to: type=inline
