name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'
  jobs:
    citation-update:
    uses: actions/checkout@v3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update CITATION.cff
    - run: |
      version=`grep -o '\d\+\.\d\+\.\d\+' package.json`
      today=`date +"%Y-%m-%d"`
      sed -i "s/^version: [[:digit:]]\{1,\}\.[[:digit:]]\{1,\}\.[[:digit:]]\{1,\}/version: $version/" CITATION.cff
      sed -i "s/[[:digit:]]\{4\}-[[:digit:]]\{2\}-[[:digit:]]\{2\}/$today/" CITATION.cff
      git commit -a -m "update version and date in CITATION.cff"

