# This action will update the CITATION.cff file for new release or hotfix branches

name: Release

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

jobs:
  citation-update:
    name: Update CITATION.cff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Autoformat CITATION.cff
        run: |
          version=`grep -o '\d\+\.\d\+\.\d\+' package.json`
          today=`date +"%Y-%m-%d"`
          sed -i "s/^version: [[:digit:]]\{1,\}\.[[:digit:]]\{1,\}\.[[:digit:]]\{1,\}/version: $version/" CITATION.cff
          sed -i "s/[[:digit:]]\{4\}-[[:digit:]]\{2\}-[[:digit:]]\{2\}/$today/" CITATION.cff
          bash ./update-citation.sh
          git commit -a -m "update version and date in CITATION.cff"

