# This workflow will run tests on the Python and Node versions defined in the Dockerfiles
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'

jobs:
  backend-test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3
    - name: Run backend tests
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: backend-test
      run: sudo mkdir -p /ci-data && sudo docker-compose --env-file .env-ci exec backend-test pytest
  frontend-test:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3
    - name: Run frontend tests
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: frontend-test
      run: sudo docker-compose --env-file .env-ci exec frontend-test yarn test
